### PR TITLE
Add angular-mocks and angular-route to dependencies

### PR DESCRIPTION
**Pull request by mischkl**

### CODE REVIEW

**Comment by alessioalex** [comment]
btw angular-mocks was already there:

https://github.com/angularjs-de/angularjs-de-seed-es6/blob/master/package.json#L27

**Comment by mischkl** [comment]
@alessioalex thx, missed that, now fixed

**Comment by mischkl** [comment]
fixes #2

**Comment by robinboehm** [comment]
+1 will merge this today :) <3

**Comment by robinboehm** [comment]
thx @mischkl :)

**Pull request merged**
